
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/sms
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

